### ISSUE TITLE
Bearer token is expected to be capitalized Bearer.

### ISSUE THREAD

**Issue by prb112** [smart-on-fhir/bulk-data-client#1]
Per https://datatracker.ietf.org/doc/html/rfc6750#section-2.1, the Bearer token is expected to be capitalized Bearer. 

```
     b64token    = 1*( ALPHA / DIGIT /
                       "-" / "." / "_" / "~" / "+" / "/" ) *"="
     credentials = "Bearer" 1*SP b64token
```

In BulkDataClient.ts line 205 the bearer is lower case. 

This had an unexpected behavior with Keycloak where it was not parseable as a Token. 

I'm raising this as it may be something to be aware of.

**Comment by vlad-ignatov** [comment]
Fixed by #4
