### ISSUE TITLE
Expose debugging header fields

### ISSUE THREAD

**Issue by mikix** [smart-on-fhir/bulk-data-client#21]
At least in Cerner's case, there are some request headers that they like to ask for when you go to them for support. Specifically in Cerner's case:

- `X-Request-Id`
- `Cerner-Correlation-Id`

If either of those headers are present, it might be nice to put them in the output or error log or something. Hard to get after the fact.

I'm sure Epic has its own version of this, which would also be nice to expose, but I don't know those off hand.

**Comment by Dtphelan1** [comment]
Just to make sure I understand correctly, the scenario is: 
- I'm making a bulk data request against a FHIR server owned by someone else (let's say Cerner)
- Something hasn't gone as expected. 
- I want to ask Cerner for help understanding why this request failed or didn't go as planned.
- Somewhere in their FHIR server's response headers, they included a `Cerner-Correlation-Id` header that they use for debugging on their end. 
- If I knew ahead of time this request would fail I could have run the requests with `NODE_DEBUG=app-request` to see all the relevant headers in my STDERR logs, but it's after the fact and I need the id's associated with the previous run that I didn't know was going to fail. 
- `CONCLUSION:` In the cases where a request fails, it would be nice to scan the response object (in this case: response headers) for metadata that's helpful when debugging later.

**Comment by mikix** [comment]
Yes.

- I usually see `X-Request-Id` not `Cerner-Correlation-Id` myself, but their support form mentions both :shrug:
- I suppose I can just always run with `NODE_DEBUG=app-request` -- I did not know about that flag (maybe surfacing that in the README would help)
- I think the Request ID is the same for a whole bulk export (worth confirming), so I was envisioning a simple print of the value up front (like the status URL is printed, along with other job start info).

**Comment by Dtphelan1** [comment]
Gonna talk with Vlad about if/where these magical headers for Request IDs could surface in the client, but either way the `README` could benefit from a line about the `NODE_DEBUG`environment variable 😄
