### ISSUE TITLE
User-Agent string is awkward

### ISSUE THREAD

**Issue by prb112** [smart-on-fhir/bulk-data-client#3]
Using the bulk-data-client to connect/test with FHIR $export and backend services I noticed the user-agent string. 

```
NODE_DEBUG=* AUTO_RETRY_TRANSIENT_ERRORS=1 SHOW_ERRORS=1 node . --config config/ibm-fhir-server.js --global --_type Patient
user-agent: Bulk Data Client <https://github.com/smart-on-fhir/bulk-data-client>
```

It appears to come from [request.js](https://github.com/smart-on-fhir/bulk-data-client/blob/main/src/lib/request.ts#L15)

```
exports.default = source_1.default.extend({
     hooks: {
         beforeRequest: [
             options => {
               options.headers["user-agent"] = "Bulk Data Client <https://github.com/smart-on-fhir/bulk-data-client>";
```

I've never seen this format for a user-agent, per Mozilla a [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) should follow: 

```
User-Agent: <product> / <product-version> <comment>
```

I think some proxies may reject this an injection attack or strip it away. 

I'm bringing this up for your awareness.  Thank you for the client, it's great.

**Comment by vlad-ignatov** [comment]
This was fixed by #4, and then it was made to show the proper version as specified in package.json
