### ISSUE TITLE
Toggling off DocumentReference attachment processing

### ISSUE THREAD

**Issue by mgold-greenway** [smart-on-fhir/bulk-data-client#6]
Looking for a configurable option to not process DocumentReference url attachments at all regardless of size or type, and didn't see anything that does that in the available params. The params used to dictate whether to inline the content of the URL attachment come close, but, in my case, even when when setting to inlineAttachmentSize to 0, individual bundles containing the attachment are placed in the 'attachment' folder (one for every line of the DocumentReference NDJSON file that has a URL attachment). The client seems to take a lot of time to iterate/process large numbers of these DocumentReference.content.attachment.url elements so I'm thinking that I'd like to be able to toggle that functionality off...

Thanks!

**Comment by vlad-ignatov** [comment]
We made some updates and there is a `downloadAttachments` option now. You can set that to `false` to disable attachment processing. Feel free to reopen if that does not work for you. Thanks!
