### ISSUE TITLE
'onCancel' handler was attached after the promise settled

### ISSUE THREAD

**Issue by sarahmcdougall** [smart-on-fhir/bulk-data-client#7]
Hello, I am trying to test the bulk data client with the [SMART Bulk Data Server](https://bulk-data.smarthealthit.org) and I am receiving the following error when running the CLI: "The `onCancel` handler was attached after the promise settled". For context, I am using the following parameters:

- `fhirUrl`: "https://bulk-data.smarthealthit.org/eyJlcnIiOiIiLCJwYWdlIjoxMDAwMCwiZHVyIjoxMCwidGx0IjoxNSwibSI6MSwic3R1IjozLCJkZWwiOjB9/fhir"
- `group`: "048d4683-703a-4311-963d-48e515a6372b" (the Neighborhood Health Plan group from the SMART Bulk Data Server)
- All other parameters used are the defaults in `config/defaults.js`

The screenshot below shows the error (as well as the npm/node versions that I am working with). The error occurs when trying to download the files (note: I have been able to run the CLI successfully with this `fhirUrl` and `group`, so this error is not consistently being thrown)
<img width="478" alt="Screen Shot 2022-11-09 at 3 21 05 PM" src="https://user-images.githubusercontent.com/87094479/200933752-fe5b7222-c967-4c7d-9de2-e1ed2110076d.png">

The `onCancel` handler error seems to be coming from the `got` dependency (based on my understanding of [this GH issue in the got repository](https://github.com/sindresorhus/got/issues/1489)).

Are there any configuration steps that I have missed that would result in this error? Thank you for your help!

**Comment by vlad-ignatov** [comment]
Right, this seems to be `got` error with no good workaround. There is newer version of the client now and it also includes the latest compatible version of got. I hope that does fix this for you.

**Comment by sarahmcdougall** [comment]
The newer version of the client fixed the issue. Thank you!
