### ISSUE TITLE
Log export metadata

### ISSUE THREAD

**Issue by gotdan** [smart-on-fhir/bulk-data-client#8]
### First cut at data we probably want to capture:

For kick-off request:
- Timestamp (there may be value in capturing all timestamps as time with local tz rather than UTC so can easily determine if time of day consistently impacts performance)
- Vendor and server info (should be available via the server's capability statement: software.name, software.version, software.releaseDate, fhirVersion)
- Server URL and/or another way to distinguish between sites
- Request parameters (possibly exclude the Patient reference list, since this could be very large?)
 
For kick-off error (when applicable):
- Timestamp
- Error code
- Error body

For status error (when applicable):
- Timestamp
- Error code
- Error body

For completion manifest (when applicable):
- Timestamp
- Resource file count
- Error file count

For each file download:
- Timestamp (start)
- File identifier (hash of output[].url ?)
- Resource type (output[].type)

For failed file downloads:
- Timestamp (end)
- File identifier (hash of output[].url ?)
- Error code
- Error content
	
For completed file downloads:
- Timestamp (end)
- File identifier (hash of output[].url ?)
- Line count 
- Size in bytes

### Design thoughts
- Option to turn logging on and off by config and command line parameter
- Could put a file in output directory of each export so it's easy for users to review and share
- Probably want to generate a unique id for each export and include it in all the log items so they're it's to import them into a data store and query over them
- ndjson would be flexible and familiar to users
- Lines could be objects with standard properties like:
	- exportId - UUID generated per export
	- timestamp - as mentioned above, maybe iso 8601 with tz
	- eventName -  e.g., "kick_off", "kick_off_error", "status_error", "manifest", "download_start", "download_end", "download_error", etc.
	- eventData - object with event specific parameters

### Open questions
- Are there other export activities or data that it would make sense to capture?
- Do we want to capture a set of client side errors like "error_writing_file"?
- Does the event format above make sense?
- How much data should we repeat in each log item for easy queryability (e.g., include resource type in all of the file related events or just in the download start and assume that users can join events on the file identifier)?

cc: @vlad-ignatov @mikix

**Comment by mikix** [comment]
We talked about this a bit in slack, and I think the only useful contributions I had were:
- Maybe worth capturing normal delays vs server is busy delays (i.e. 202 vs 429) and the server-requested delay (or absent that, the client-decided delay)
- Don't forget about capturing performance of downloading the error files too (when the server provides an `error` array)

So here's what I'd add on to your overview, Dan:
- For each of those categories you listed, they should have some `type` field like `status-request` or `error-download` etc to distinguish them. (this felt assumed, but I'm just making that explicit)
- For each of those categories you listed, they can all appear multiple times.
- For any captured request, if there is a delay (202 or 429), capture the delay type (status code) and the delay amount and omit other fields.

Sound reasonable? But I like this! Next step might be a more explicit spec-style doc listing the request categories and fields for each?

**Comment by gotdan** [comment]
Sounds good! I started a wiki page for us to define how the specific log items should look at https://github.com/smart-on-fhir/bulk-data-client/wiki/Bulk-Data-Export-Log-Items . @mikix @vlad-ignatov - please expand, and highlight if there are any of the properties that might be challenging to capture in your client implementations.
