### ISSUE TITLE
`ERR_STREAM_PREMATURE_CLOSE` error on early `destroy()` when downloading ndjson

### ISSUE THREAD

**Issue by sarahmcdougall** [smart-on-fhir/bulk-data-client#9]
When testing the bulk data client with the [SMART Bulk Data Server](https://bulk-data.smarthealthit.org/), I receive the following error from the CLI: `Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close`.

To reproduce, use the following parameters:
* `fhirUrl`: https://bulk-data.smarthealthit.org/eyJlcnIiOiIiLCJwYWdlIjoxMDAwMCwiZHVyIjoxMCwidGx0IjoxNSwibSI6MSwic3R1IjozLCJkZWwiOjB9/fhir
* `group`: 048d4683-703a-4311-963d-48e515a6372b
* All other parameters used are the defaults in `config/defaults.js`

See the screenshot below:
![Screen Shot 2023-01-04 at 10 43 18 AM](https://user-images.githubusercontent.com/87094479/210592982-e08155b2-ff25-4ecb-8e4a-5fceb84decd8.png)

For reference, I am using Node.js version 18.12.0. I do not receive this error on Node.js version 16. I believe this issue may be related to the `got` dependency upgrade to version 11.8.6. I [commented on this open Github issue](https://github.com/sindresorhus/got/issues/2041#issuecomment-1370993748) to bring awareness of this issue to the `got` team.

**Comment by vlad-ignatov** [comment]
Thanks @sarahmcdougall, I doubt we are dealing with `got` issue in this case. I pushed some changes that should hopefully fix this issue. The NodeJS version shouldn't matter. Can you verify if it works for you?

**Comment by sarahmcdougall** [comment]
Apologies for the late reply - the changes fixed the issue for me! Thank you!
